# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Jar
        run: mvn -B package --file pom.xml
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Decrypt Bose Properties
        run: ./.github/scripts/decrypt_boseproperties.sh
        env:
          BOSE_PROPERTIES_KEY: ${{ secrets.BOSE_PROPERTIES_KEY }}
      - name: Test printing your secret (Remove this step in production)
        run: cat bose.properties
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            JAR_FILE=target/SoundTouchControl-3.2.jar
            BOSE=bose.properties
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/soundtouch:latest
